vim.pack.add({
    'https://github.com/nvim-treesitter/nvim-treesitter',
    'https://github.com/nvim-treesitter/nvim-treesitter-context'
})
vim.api.nvim_create_autocmd('FileType', { callback = function() pcall(vim.treesitter.start) end, })
require('nvim-treesitter').install {
    'bash',
    'python',
    'nix',
    'perl',
    'lua',
    --
    'json',
    'yaml',
    'toml',
    'ini',
    'xml',
    --
    'awk',
    'regex',
    --
    'html',
    'typescript',
    --
    'markdown',
    'markdown_inline',
    --
    'git_config',
    'git_rebase',
    'gitcommit',
    'gitignore',
    'gitattributes',
    'ssh_config',
}
