vim.g.loaded_node_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_python3_provider = 0
vim.g.loaded_ruby_provider = 0
vim.g.mapleader = ' '
vim.g.maplocalleader = '\\'
vim.o.mouse = 'a'
vim.o.scrolloff = 10
vim.o.signcolumn = 'yes'
vim.o.clipboard = 'unnamedplus'
vim.o.termguicolors = true
vim.o.wrap = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.smarttab = true
vim.o.smartindent = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.hlsearch = false
vim.o.undofile = true
vim.o.inccommand = 'split'
require('config')
